//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TRIMESTRE
    {
        public int TRI_ID_TRIMESTRE { get; set; }
        public string TRI_DESCRIPCION { get; set; }
        public Nullable<bool> TRI_ESTATUS_REGISTRO { get; set; }
        public Nullable<System.DateTime> TRI_FECHA_REGISTRO { get; set; }
    }
}
