//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_TraductorSector1
    {
        public int IdSectorActual { get; set; }
        public string DescripcionSector { get; set; }
        public int IdSectorAnterior { get; set; }
        public Nullable<int> IdAplicacion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
