//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_DiasInhabiles
    {
        public int Id_DiaInhabil { get; set; }
        public System.DateTime Alta { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public int Dia { get; set; }
        public int Mes { get; set; }
        public Nullable<int> Anio { get; set; }
        public int Fk_IdCalendario { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
