//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_TraductorInstitucion1
    {
        public int IdInstitucionActual { get; set; }
        public string DescripcionInstitucion { get; set; }
        public int IdInstitucionAnterior { get; set; }
        public Nullable<int> IdNatJuridica { get; set; }
        public Nullable<int> Fk_IdSector { get; set; }
        public Nullable<int> Fk_IdApliacion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Cat_Institucion Cat_Institucion { get; set; }
    }
}
