//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_UsoGenerico
    {
        public Cat_UsoGenerico()
        {
            this.Cat_UsoEspecifico = new HashSet<Cat_UsoEspecifico>();
        }
    
        public int IdUsoGenerico { get; set; }
        public string DescripcionUsoGenerico { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual ICollection<Cat_UsoEspecifico> Cat_UsoEspecifico { get; set; }
    }
}
