//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_TipoAsentamiento
    {
        public Cat_TipoAsentamiento()
        {
            this.Cat_Asentamiento = new HashSet<Cat_Asentamiento>();
        }
    
        public int IdTipoAsentamiento { get; set; }
        public string DescripcionTipoAsentamiento { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual ICollection<Cat_Asentamiento> Cat_Asentamiento { get; set; }
    }
}
