//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Zona
    {
        public Cat_Zona()
        {
            this.Cat_CodigoPostal = new HashSet<Cat_CodigoPostal>();
        }
    
        public int IdZona { get; set; }
        public string DescripcionZona { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual ICollection<Cat_CodigoPostal> Cat_CodigoPostal { get; set; }
    }
}
