//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_TipoExcepcionNormativaContrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_TipoExcepcionNormativaContrato()
        {
            this.ExcepcionNormativaContratoArrto = new HashSet<ExcepcionNormativaContratoArrto>();
        }
    
        public byte IdTipoExcepcionNormativaContrato { get; set; }
        public string DescripcionExcepcionTipoNormativa { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcepcionNormativaContratoArrto> ExcepcionNormativaContratoArrto { get; set; }
    }
}
