//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_CodigoPostal
    {
        public int IdLocalidad { get; set; }
        public int Fk_IdEstado { get; set; }
        public int Fk_IdMunicipio { get; set; }
        public string DescripcionColonia { get; set; }
        public string LocalidadCP { get; set; }
        public int Fk_IdTipoAsenta { get; set; }
        public int Fk_IdZona { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Cat_Estado Cat_Estado { get; set; }
        public virtual Cat_Municipio Cat_Municipio { get; set; }
        public virtual Cat_TipoAsenta Cat_TipoAsenta { get; set; }
        public virtual Cat_Zona Cat_Zona { get; set; }
    }
}
