//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Localidades
    {
        public Cat_Localidades()
        {
            this.Cat_Asentamiento = new HashSet<Cat_Asentamiento>();
        }
    
        public int IdLocalidad { get; set; }
        public int Fk_IdMunicipio { get; set; }
        public string DescripcionLocalidad { get; set; }
        public string Ambito { get; set; }
        public double Latitud { get; set; }
        public double Longitud { get; set; }
        public double Lat_Dec { get; set; }
        public double Lon_Dec { get; set; }
        public double Altitud { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual ICollection<Cat_Asentamiento> Cat_Asentamiento { get; set; }
        public virtual Cat_Municipio Cat_Municipio { get; set; }
    }
}
