//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CAT_NuevaEntities : DbContext
    {
        public DB_CAT_NuevaEntities()
            : base("name=DB_CAT_NuevaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cat_Bancos> Cat_Bancos { get; set; }
        public virtual DbSet<Cat_CodigoPostal> Cat_CodigoPostal { get; set; }
        public virtual DbSet<Cat_DiasInhabiles> Cat_DiasInhabiles { get; set; }
        public virtual DbSet<Cat_Institucion> Cat_Institucion { get; set; }
        public virtual DbSet<Cat_Mes> Cat_Mes { get; set; }
        public virtual DbSet<Cat_Municipio> Cat_Municipio { get; set; }
        public virtual DbSet<Cat_Pais> Cat_Pais { get; set; }
    }
}
