//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArrendamientoInmuebleEntities : DbContext
    {
        public ArrendamientoInmuebleEntities()
            : base("name=ArrendamientoInmuebleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AplicacionConcepto> AplicacionConcepto { get; set; }
        public virtual DbSet<AreaPrioridad> AreaPrioridad { get; set; }
        public virtual DbSet<BitacoraExcepcion> BitacoraExcepcion { get; set; }
        public virtual DbSet<BitacoraSistema> BitacoraSistema { get; set; }
        public virtual DbSet<Cat_Indicador> Cat_Indicador { get; set; }
        public virtual DbSet<Cat_InstitucionContratosDBCATNueva> Cat_InstitucionContratosDBCATNueva { get; set; }
        public virtual DbSet<Cat_InstitucionContratosHistorico> Cat_InstitucionContratosHistorico { get; set; }
        public virtual DbSet<Cat_Parametro> Cat_Parametro { get; set; }
        public virtual DbSet<Cat_Prioridad> Cat_Prioridad { get; set; }
        public virtual DbSet<Cat_Tabla> Cat_Tabla { get; set; }
        public virtual DbSet<Cat_Tema> Cat_Tema { get; set; }
        public virtual DbSet<Cat_TipoArrendamiento> Cat_TipoArrendamiento { get; set; }
        public virtual DbSet<Cat_TipoContratacion> Cat_TipoContratacion { get; set; }
        public virtual DbSet<Cat_TipoContrato> Cat_TipoContrato { get; set; }
        public virtual DbSet<Cat_TipoExcepcionNormativaContrato> Cat_TipoExcepcionNormativaContrato { get; set; }
        public virtual DbSet<Cat_TipoOcupacion> Cat_TipoOcupacion { get; set; }
        public virtual DbSet<Cat_TipoPersonaReferencia> Cat_TipoPersonaReferencia { get; set; }
        public virtual DbSet<Concepto> Concepto { get; set; }
        public virtual DbSet<ConceptoAccesibilidad> ConceptoAccesibilidad { get; set; }
        public virtual DbSet<ContratoArrto> ContratoArrto { get; set; }
        public virtual DbSet<ContratoArrto_Historico> ContratoArrto_Historico { get; set; }
        public virtual DbSet<ContratosArrtoRIUF> ContratosArrtoRIUF { get; set; }
        public virtual DbSet<ContratosVigentes> ContratosVigentes { get; set; }
        public virtual DbSet<Convenio_Modificatorio> Convenio_Modificatorio { get; set; }
        public virtual DbSet<DatosAdicionalesDireccion> DatosAdicionalesDireccion { get; set; }
        public virtual DbSet<DatosAdicionalesInmueble> DatosAdicionalesInmueble { get; set; }
        public virtual DbSet<EmisionOpinonContrato> EmisionOpinonContrato { get; set; }
        public virtual DbSet<ExcepcionNormativaContratoArrto> ExcepcionNormativaContratoArrto { get; set; }
        public virtual DbSet<Inmueble> Inmueble { get; set; }
        public virtual DbSet<InmuebleArrendamiento> InmuebleArrendamiento { get; set; }
        public virtual DbSet<InmuebleNvosSinRIUF> InmuebleNvosSinRIUF { get; set; }
        public virtual DbSet<InmuebleSinRIUF> InmuebleSinRIUF { get; set; }
        public virtual DbSet<JustipreciacionArrto> JustipreciacionArrto { get; set; }
        public virtual DbSet<JustipreciacionExt> JustipreciacionExt { get; set; }
        public virtual DbSet<Movimiento> Movimiento { get; set; }
        public virtual DbSet<NoUtiliAuditoria2019T> NoUtiliAuditoria2019T { get; set; }
        public virtual DbSet<NoUtiliAuditoria2019TProduccion> NoUtiliAuditoria2019TProduccion { get; set; }
        public virtual DbSet<PersonaReferencia> PersonaReferencia { get; set; }
        public virtual DbSet<PlazasInmueble> PlazasInmueble { get; set; }
        public virtual DbSet<Rel_ConceptoRespValor> Rel_ConceptoRespValor { get; set; }
        public virtual DbSet<ReporteTotal> ReporteTotal { get; set; }
        public virtual DbSet<Respuesta> Respuesta { get; set; }
        public virtual DbSet<RespuestaConcepto> RespuestaConcepto { get; set; }
        public virtual DbSet<RIUF> RIUF { get; set; }
        public virtual DbSet<SelloDigital> SelloDigital { get; set; }
        public virtual DbSet<Cat_CampoReporte> Cat_CampoReporte { get; set; }
        public virtual DbSet<Cat_Documento> Cat_Documento { get; set; }
        public virtual DbSet<dbcatnueva_instituciones> dbcatnueva_instituciones { get; set; }
        public virtual DbSet<InmuebleFebreroSinRIUF> InmuebleFebreroSinRIUF { get; set; }
        public virtual DbSet<PlazasInmueble_20171205> PlazasInmueble_20171205 { get; set; }
        public virtual DbSet<PlazasInmuebleMod> PlazasInmuebleMod { get; set; }
        public virtual DbSet<RepRFI_RIUF> RepRFI_RIUF { get; set; }
        public virtual DbSet<TRADUCTOR_cat> TRADUCTOR_cat { get; set; }
        public virtual DbSet<TraductorRUSP_INST> TraductorRUSP_INST { get; set; }
        public virtual DbSet<TraductorRUSP_Sector> TraductorRUSP_Sector { get; set; }
    }
}
