//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_TipoIdentificacionInstExpide
    {
        public int IdIdentificacionExpide { get; set; }
        public int FK_IdTipoIdentificacion { get; set; }
        public int FK_IdInstExpide { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Cat_InstitucionExpide Cat_InstitucionExpide { get; set; }
        public virtual Cat_TipoIdentificacion Cat_TipoIdentificacion { get; set; }
    }
}
