//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparaciónNoUtili
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelCargoUnidadNeg
    {
        public RelCargoUnidadNeg()
        {
            this.Cat_Emisor = new HashSet<Cat_Emisor>();
        }
    
        public int IdRelCargoUnidadNeg { get; set; }
        public int Fk_IdCargo { get; set; }
        public int Fk_IdUnidadNegocio { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Cat_Cargo Cat_Cargo { get; set; }
        public virtual ICollection<Cat_Emisor> Cat_Emisor { get; set; }
        public virtual Cat_UnidadNegocio Cat_UnidadNegocio { get; set; }
    }
}
